import Header from "@/Header";
import { Footer } from "@/Footer";
import { Menu } from "@/Menu";
import { Login } from "@/Login";
import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "React App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Login /> 
        <Header />
          <Menu />
          {
            /* 
          children 
          */
          }
         <Footer />
        </body>
    </html>
  );
}
